# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import training_pb2 as training__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in training_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingDaemonStub(object):
    """Internal RPC between the Ollama Go daemon and the Python GPU training daemon.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/ollama.training.v1.TrainingDaemon/Health',
                request_serializer=training__pb2.HealthRequest.SerializeToString,
                response_deserializer=training__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.SubmitJob = channel.unary_unary(
                '/ollama.training.v1.TrainingDaemon/SubmitJob',
                request_serializer=training__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=training__pb2.SubmitJobResponse.FromString,
                _registered_method=True)
        self.JobStatus = channel.unary_unary(
                '/ollama.training.v1.TrainingDaemon/JobStatus',
                request_serializer=training__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=training__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/ollama.training.v1.TrainingDaemon/CancelJob',
                request_serializer=training__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=training__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/ollama.training.v1.TrainingDaemon/ListJobs',
                request_serializer=training__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=training__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/ollama.training.v1.TrainingDaemon/StreamEvents',
                request_serializer=training__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=training__pb2.TrainingEvent.FromString,
                _registered_method=True)
        self.Unload = channel.unary_unary(
                '/ollama.training.v1.TrainingDaemon/Unload',
                request_serializer=training__pb2.UnloadRequest.SerializeToString,
                response_deserializer=training__pb2.UnloadResponse.FromString,
                _registered_method=True)
        self.AckVRAMHeadroom = channel.unary_unary(
                '/ollama.training.v1.TrainingDaemon/AckVRAMHeadroom',
                request_serializer=training__pb2.AckVRAMHeadroomRequest.SerializeToString,
                response_deserializer=training__pb2.AckVRAMHeadroomResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/ollama.training.v1.TrainingDaemon/Shutdown',
                request_serializer=training__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=training__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class TrainingDaemonServicer(object):
    """Internal RPC between the Ollama Go daemon and the Python GPU training daemon.

    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Server streams job-scoped events (progress, completion, OOM). Filter by job_id if set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckVRAMHeadroom(self, request, context):
        """After Go evicts inference runners, call this so Python can retry GPU allocation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingDaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=training__pb2.HealthRequest.FromString,
                    response_serializer=training__pb2.HealthResponse.SerializeToString,
            ),
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=training__pb2.SubmitJobRequest.FromString,
                    response_serializer=training__pb2.SubmitJobResponse.SerializeToString,
            ),
            'JobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.JobStatus,
                    request_deserializer=training__pb2.JobStatusRequest.FromString,
                    response_serializer=training__pb2.JobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=training__pb2.CancelJobRequest.FromString,
                    response_serializer=training__pb2.CancelJobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=training__pb2.ListJobsRequest.FromString,
                    response_serializer=training__pb2.ListJobsResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=training__pb2.StreamEventsRequest.FromString,
                    response_serializer=training__pb2.TrainingEvent.SerializeToString,
            ),
            'Unload': grpc.unary_unary_rpc_method_handler(
                    servicer.Unload,
                    request_deserializer=training__pb2.UnloadRequest.FromString,
                    response_serializer=training__pb2.UnloadResponse.SerializeToString,
            ),
            'AckVRAMHeadroom': grpc.unary_unary_rpc_method_handler(
                    servicer.AckVRAMHeadroom,
                    request_deserializer=training__pb2.AckVRAMHeadroomRequest.FromString,
                    response_serializer=training__pb2.AckVRAMHeadroomResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=training__pb2.ShutdownRequest.FromString,
                    response_serializer=training__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ollama.training.v1.TrainingDaemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ollama.training.v1.TrainingDaemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingDaemon(object):
    """Internal RPC between the Ollama Go daemon and the Python GPU training daemon.

    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/Health',
            training__pb2.HealthRequest.SerializeToString,
            training__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/SubmitJob',
            training__pb2.SubmitJobRequest.SerializeToString,
            training__pb2.SubmitJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/JobStatus',
            training__pb2.JobStatusRequest.SerializeToString,
            training__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/CancelJob',
            training__pb2.CancelJobRequest.SerializeToString,
            training__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/ListJobs',
            training__pb2.ListJobsRequest.SerializeToString,
            training__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/StreamEvents',
            training__pb2.StreamEventsRequest.SerializeToString,
            training__pb2.TrainingEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/Unload',
            training__pb2.UnloadRequest.SerializeToString,
            training__pb2.UnloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckVRAMHeadroom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/AckVRAMHeadroom',
            training__pb2.AckVRAMHeadroomRequest.SerializeToString,
            training__pb2.AckVRAMHeadroomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ollama.training.v1.TrainingDaemon/Shutdown',
            training__pb2.ShutdownRequest.SerializeToString,
            training__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
