//go:build darwin && arm64

// Code generated by scripts/build/gen_ggml_metal_embed.sh. DO NOT EDIT.
.section __DATA,__ggml_metallib
.globl _ggml_metallib_fa_aux_start
_ggml_metallib_fa_aux_start:
.incbin "ggml-metal-embed-fa_aux.metal"
.globl _ggml_metallib_fa_aux_end
_ggml_metallib_fa_aux_end:
.globl _ggml_metallib_fa_f16_start
_ggml_metallib_fa_f16_start:
.incbin "ggml-metal-embed-fa_f16.metal"
.globl _ggml_metallib_fa_f16_end
_ggml_metallib_fa_f16_end:
.globl _ggml_metallib_fa_f32_start
_ggml_metallib_fa_f32_start:
.incbin "ggml-metal-embed-fa_f32.metal"
.globl _ggml_metallib_fa_f32_end
_ggml_metallib_fa_f32_end:
.globl _ggml_metallib_fa_q4_0_start
_ggml_metallib_fa_q4_0_start:
.incbin "ggml-metal-embed-fa_q4_0.metal"
.globl _ggml_metallib_fa_q4_0_end
_ggml_metallib_fa_q4_0_end:
.globl _ggml_metallib_fa_q4_1_start
_ggml_metallib_fa_q4_1_start:
.incbin "ggml-metal-embed-fa_q4_1.metal"
.globl _ggml_metallib_fa_q4_1_end
_ggml_metallib_fa_q4_1_end:
.globl _ggml_metallib_fa_q5_0_start
_ggml_metallib_fa_q5_0_start:
.incbin "ggml-metal-embed-fa_q5_0.metal"
.globl _ggml_metallib_fa_q5_0_end
_ggml_metallib_fa_q5_0_end:
.globl _ggml_metallib_fa_q5_1_start
_ggml_metallib_fa_q5_1_start:
.incbin "ggml-metal-embed-fa_q5_1.metal"
.globl _ggml_metallib_fa_q5_1_end
_ggml_metallib_fa_q5_1_end:
.globl _ggml_metallib_fa_q8_0_start
_ggml_metallib_fa_q8_0_start:
.incbin "ggml-metal-embed-fa_q8_0.metal"
.globl _ggml_metallib_fa_q8_0_end
_ggml_metallib_fa_q8_0_end:
.globl _ggml_metallib_fa_vec_f16_start
_ggml_metallib_fa_vec_f16_start:
.incbin "ggml-metal-embed-fa_vec_f16.metal"
.globl _ggml_metallib_fa_vec_f16_end
_ggml_metallib_fa_vec_f16_end:
.globl _ggml_metallib_fa_vec_f32_start
_ggml_metallib_fa_vec_f32_start:
.incbin "ggml-metal-embed-fa_vec_f32.metal"
.globl _ggml_metallib_fa_vec_f32_end
_ggml_metallib_fa_vec_f32_end:
.globl _ggml_metallib_fa_vec_q4_0_start
_ggml_metallib_fa_vec_q4_0_start:
.incbin "ggml-metal-embed-fa_vec_q4_0.metal"
.globl _ggml_metallib_fa_vec_q4_0_end
_ggml_metallib_fa_vec_q4_0_end:
.globl _ggml_metallib_fa_vec_q4_1_start
_ggml_metallib_fa_vec_q4_1_start:
.incbin "ggml-metal-embed-fa_vec_q4_1.metal"
.globl _ggml_metallib_fa_vec_q4_1_end
_ggml_metallib_fa_vec_q4_1_end:
.globl _ggml_metallib_fa_vec_q5_0_start
_ggml_metallib_fa_vec_q5_0_start:
.incbin "ggml-metal-embed-fa_vec_q5_0.metal"
.globl _ggml_metallib_fa_vec_q5_0_end
_ggml_metallib_fa_vec_q5_0_end:
.globl _ggml_metallib_fa_vec_q5_1_start
_ggml_metallib_fa_vec_q5_1_start:
.incbin "ggml-metal-embed-fa_vec_q5_1.metal"
.globl _ggml_metallib_fa_vec_q5_1_end
_ggml_metallib_fa_vec_q5_1_end:
.globl _ggml_metallib_fa_vec_q8_0_start
_ggml_metallib_fa_vec_q8_0_start:
.incbin "ggml-metal-embed-fa_vec_q8_0.metal"
.globl _ggml_metallib_fa_vec_q8_0_end
_ggml_metallib_fa_vec_q8_0_end:
.globl _ggml_metallib_mul_mv_start
_ggml_metallib_mul_mv_start:
.incbin "ggml-metal-embed-mul_mv.metal"
.globl _ggml_metallib_mul_mv_end
_ggml_metallib_mul_mv_end:
.globl _ggml_metallib_mul_mm_start
_ggml_metallib_mul_mm_start:
.incbin "ggml-metal-embed-mul_mm.metal"
.globl _ggml_metallib_mul_mm_end
_ggml_metallib_mul_mm_end:
.globl _ggml_metallib_quantize_start
_ggml_metallib_quantize_start:
.incbin "ggml-metal-embed-quantize.metal"
.globl _ggml_metallib_quantize_end
_ggml_metallib_quantize_end:
.globl _ggml_metallib_softmax_start
_ggml_metallib_softmax_start:
.incbin "ggml-metal-embed-softmax.metal"
.globl _ggml_metallib_softmax_end
_ggml_metallib_softmax_end:
.globl _ggml_metallib_norm_start
_ggml_metallib_norm_start:
.incbin "ggml-metal-embed-norm.metal"
.globl _ggml_metallib_norm_end
_ggml_metallib_norm_end:
.globl _ggml_metallib_unary_start
_ggml_metallib_unary_start:
.incbin "ggml-metal-embed-unary.metal"
.globl _ggml_metallib_unary_end
_ggml_metallib_unary_end:
.globl _ggml_metallib_binbcast_start
_ggml_metallib_binbcast_start:
.incbin "ggml-metal-embed-binbcast.metal"
.globl _ggml_metallib_binbcast_end
_ggml_metallib_binbcast_end:
.globl _ggml_metallib_reduce_start
_ggml_metallib_reduce_start:
.incbin "ggml-metal-embed-reduce.metal"
.globl _ggml_metallib_reduce_end
_ggml_metallib_reduce_end:
.globl _ggml_metallib_tri_start
_ggml_metallib_tri_start:
.incbin "ggml-metal-embed-tri.metal"
.globl _ggml_metallib_tri_end
_ggml_metallib_tri_end:
.globl _ggml_metallib_ssm_start
_ggml_metallib_ssm_start:
.incbin "ggml-metal-embed-ssm.metal"
.globl _ggml_metallib_ssm_end
_ggml_metallib_ssm_end:
.globl _ggml_metallib_wkv_start
_ggml_metallib_wkv_start:
.incbin "ggml-metal-embed-wkv.metal"
.globl _ggml_metallib_wkv_end
_ggml_metallib_wkv_end:
.globl _ggml_metallib_gated_delta_net_start
_ggml_metallib_gated_delta_net_start:
.incbin "ggml-metal-embed-gated_delta_net.metal"
.globl _ggml_metallib_gated_delta_net_end
_ggml_metallib_gated_delta_net_end:
.globl _ggml_metallib_solve_tri_start
_ggml_metallib_solve_tri_start:
.incbin "ggml-metal-embed-solve_tri.metal"
.globl _ggml_metallib_solve_tri_end
_ggml_metallib_solve_tri_end:
.globl _ggml_metallib_rope_start
_ggml_metallib_rope_start:
.incbin "ggml-metal-embed-rope.metal"
.globl _ggml_metallib_rope_end
_ggml_metallib_rope_end:
.globl _ggml_metallib_conv_start
_ggml_metallib_conv_start:
.incbin "ggml-metal-embed-conv.metal"
.globl _ggml_metallib_conv_end
_ggml_metallib_conv_end:
.globl _ggml_metallib_upscale_start
_ggml_metallib_upscale_start:
.incbin "ggml-metal-embed-upscale.metal"
.globl _ggml_metallib_upscale_end
_ggml_metallib_upscale_end:
.globl _ggml_metallib_argsort_start
_ggml_metallib_argsort_start:
.incbin "ggml-metal-embed-argsort.metal"
.globl _ggml_metallib_argsort_end
_ggml_metallib_argsort_end:
.globl _ggml_metallib_pool_start
_ggml_metallib_pool_start:
.incbin "ggml-metal-embed-pool.metal"
.globl _ggml_metallib_pool_end
_ggml_metallib_pool_end:
.globl _ggml_metallib_misc_start
_ggml_metallib_misc_start:
.incbin "ggml-metal-embed-misc.metal"
.globl _ggml_metallib_misc_end
_ggml_metallib_misc_end:
