//go:build darwin && arm64

// Code generated by scripts/build/gen_ggml_metal_embed.sh. DO NOT EDIT.
.section __DATA,__ggml_metallib
.globl _ggml_metallib_fa_start
_ggml_metallib_fa_start:
.incbin "ggml-metal-embed-fa.metal"
.globl _ggml_metallib_fa_end
_ggml_metallib_fa_end:
.globl _ggml_metallib_mul_mv_start
_ggml_metallib_mul_mv_start:
.incbin "ggml-metal-embed-mul_mv.metal"
.globl _ggml_metallib_mul_mv_end
_ggml_metallib_mul_mv_end:
.globl _ggml_metallib_mul_mm_start
_ggml_metallib_mul_mm_start:
.incbin "ggml-metal-embed-mul_mm.metal"
.globl _ggml_metallib_mul_mm_end
_ggml_metallib_mul_mm_end:
.globl _ggml_metallib_quantize_start
_ggml_metallib_quantize_start:
.incbin "ggml-metal-embed-quantize.metal"
.globl _ggml_metallib_quantize_end
_ggml_metallib_quantize_end:
.globl _ggml_metallib_softmax_start
_ggml_metallib_softmax_start:
.incbin "ggml-metal-embed-softmax.metal"
.globl _ggml_metallib_softmax_end
_ggml_metallib_softmax_end:
.globl _ggml_metallib_norm_start
_ggml_metallib_norm_start:
.incbin "ggml-metal-embed-norm.metal"
.globl _ggml_metallib_norm_end
_ggml_metallib_norm_end:
.globl _ggml_metallib_unary_start
_ggml_metallib_unary_start:
.incbin "ggml-metal-embed-unary.metal"
.globl _ggml_metallib_unary_end
_ggml_metallib_unary_end:
.globl _ggml_metallib_binbcast_start
_ggml_metallib_binbcast_start:
.incbin "ggml-metal-embed-binbcast.metal"
.globl _ggml_metallib_binbcast_end
_ggml_metallib_binbcast_end:
.globl _ggml_metallib_reduce_start
_ggml_metallib_reduce_start:
.incbin "ggml-metal-embed-reduce.metal"
.globl _ggml_metallib_reduce_end
_ggml_metallib_reduce_end:
.globl _ggml_metallib_tri_start
_ggml_metallib_tri_start:
.incbin "ggml-metal-embed-tri.metal"
.globl _ggml_metallib_tri_end
_ggml_metallib_tri_end:
.globl _ggml_metallib_ssm_start
_ggml_metallib_ssm_start:
.incbin "ggml-metal-embed-ssm.metal"
.globl _ggml_metallib_ssm_end
_ggml_metallib_ssm_end:
.globl _ggml_metallib_wkv_start
_ggml_metallib_wkv_start:
.incbin "ggml-metal-embed-wkv.metal"
.globl _ggml_metallib_wkv_end
_ggml_metallib_wkv_end:
.globl _ggml_metallib_gated_delta_net_start
_ggml_metallib_gated_delta_net_start:
.incbin "ggml-metal-embed-gated_delta_net.metal"
.globl _ggml_metallib_gated_delta_net_end
_ggml_metallib_gated_delta_net_end:
.globl _ggml_metallib_solve_tri_start
_ggml_metallib_solve_tri_start:
.incbin "ggml-metal-embed-solve_tri.metal"
.globl _ggml_metallib_solve_tri_end
_ggml_metallib_solve_tri_end:
.globl _ggml_metallib_rope_start
_ggml_metallib_rope_start:
.incbin "ggml-metal-embed-rope.metal"
.globl _ggml_metallib_rope_end
_ggml_metallib_rope_end:
.globl _ggml_metallib_conv_start
_ggml_metallib_conv_start:
.incbin "ggml-metal-embed-conv.metal"
.globl _ggml_metallib_conv_end
_ggml_metallib_conv_end:
.globl _ggml_metallib_upscale_start
_ggml_metallib_upscale_start:
.incbin "ggml-metal-embed-upscale.metal"
.globl _ggml_metallib_upscale_end
_ggml_metallib_upscale_end:
.globl _ggml_metallib_argsort_start
_ggml_metallib_argsort_start:
.incbin "ggml-metal-embed-argsort.metal"
.globl _ggml_metallib_argsort_end
_ggml_metallib_argsort_end:
.globl _ggml_metallib_pool_start
_ggml_metallib_pool_start:
.incbin "ggml-metal-embed-pool.metal"
.globl _ggml_metallib_pool_end
_ggml_metallib_pool_end:
.globl _ggml_metallib_misc_start
_ggml_metallib_misc_start:
.incbin "ggml-metal-embed-misc.metal"
.globl _ggml_metallib_misc_end
_ggml_metallib_misc_end:
.globl _ggml_metallib_turbo3_start
_ggml_metallib_turbo3_start:
.incbin "ggml-metal-embed-turbo3.metal"
.globl _ggml_metallib_turbo3_end
_ggml_metallib_turbo3_end:
.globl _ggml_metallib_turbo4_start
_ggml_metallib_turbo4_start:
.incbin "ggml-metal-embed-turbo4.metal"
.globl _ggml_metallib_turbo4_end
_ggml_metallib_turbo4_end:
.globl _ggml_metallib_turbo3_tcq_start
_ggml_metallib_turbo3_tcq_start:
.incbin "ggml-metal-embed-turbo3_tcq.metal"
.globl _ggml_metallib_turbo3_tcq_end
_ggml_metallib_turbo3_tcq_end:
.globl _ggml_metallib_qjl_start
_ggml_metallib_qjl_start:
.incbin "ggml-metal-embed-qjl.metal"
.globl _ggml_metallib_qjl_end
_ggml_metallib_qjl_end:
.globl _ggml_metallib_qjl_set_rows_start
_ggml_metallib_qjl_set_rows_start:
.incbin "ggml-metal-embed-qjl_set_rows.metal"
.globl _ggml_metallib_qjl_set_rows_end
_ggml_metallib_qjl_set_rows_end:
.globl _ggml_metallib_tbq_set_rows_start
_ggml_metallib_tbq_set_rows_start:
.incbin "ggml-metal-embed-tbq_set_rows.metal"
.globl _ggml_metallib_tbq_set_rows_end
_ggml_metallib_tbq_set_rows_end:
.globl _ggml_metallib_polar_set_rows_start
_ggml_metallib_polar_set_rows_start:
.incbin "ggml-metal-embed-polar_set_rows.metal"
.globl _ggml_metallib_polar_set_rows_end
_ggml_metallib_polar_set_rows_end:
.globl _ggml_metallib_polar_start
_ggml_metallib_polar_start:
.incbin "ggml-metal-embed-polar.metal"
.globl _ggml_metallib_polar_end
_ggml_metallib_polar_end:
.globl _ggml_metallib_polar_preht_start
_ggml_metallib_polar_preht_start:
.incbin "ggml-metal-embed-polar_preht.metal"
.globl _ggml_metallib_polar_preht_end
_ggml_metallib_polar_preht_end:
.globl _ggml_metallib_fused_attn_qjl_tbq_start
_ggml_metallib_fused_attn_qjl_tbq_start:
.incbin "ggml-metal-embed-fused_attn_qjl_tbq.metal"
.globl _ggml_metallib_fused_attn_qjl_tbq_end
_ggml_metallib_fused_attn_qjl_tbq_end:
.globl _ggml_metallib_fused_attn_qjl_polar_start
_ggml_metallib_fused_attn_qjl_polar_start:
.incbin "ggml-metal-embed-fused_attn_qjl_polar.metal"
.globl _ggml_metallib_fused_attn_qjl_polar_end
_ggml_metallib_fused_attn_qjl_polar_end:
.globl _ggml_metallib_istft_start
_ggml_metallib_istft_start:
.incbin "ggml-metal-embed-istft.metal"
.globl _ggml_metallib_istft_end
_ggml_metallib_istft_end:
.globl _ggml_metallib_m4_fused_swiglu_start
_ggml_metallib_m4_fused_swiglu_start:
.incbin "ggml-metal-embed-m4_fused_swiglu.metal"
.globl _ggml_metallib_m4_fused_swiglu_end
_ggml_metallib_m4_fused_swiglu_end:
