//go:build darwin && arm64

package metal

// Embedded Metal shader source for the ggml Metal backend (GGML_METAL_EMBED_LIBRARY).
// Regenerate after editing ggml-metal.metal or syncing ggml vendor:
//
//	GOFLAGS=-mod=mod go generate ./ml/backend/ggml/ggml/src/ggml-metal/
//
// Why: macOS JIT-specializes kernels from this embed at runtime (e.g. sigmoid
// kernel_unary_f32_f32_op=102 for qwen35 gated SSM). A stale embed lets model
// load succeed but first decode crash with "Function kernel_unary_f32_f32 was not found".
// build_zerollama_mac.sh runs go generate automatically. See docs/qwen35-apple-silicon.md.
//
//go:generate sh -c "{ echo // Code generated by 'go generate'. DO NOT EDIT.; sed -e '/__embed_ggml-common.h__/r ../ggml-common.h' -e '/__embed_ggml-common.h__/d' -e '/#include \"ggml-metal-impl.h\"/r ggml-metal-impl.h' -e '/#include \"ggml-metal-impl.h\"/d' ggml-metal.metal; } >ggml-metal-embed.metal"

// #cgo CXXFLAGS: -std=c++17
// #cgo CPPFLAGS: -DGGML_METAL_NDEBUG -DGGML_METAL_EMBED_LIBRARY -DGGML_METAL_HAS_BF16 -I.. -I../../include
// #cgo LDFLAGS: -framework Metal -framework MetalKit -framework IOSurface
import "C"
