//go:build darwin && arm64

package metal

// Embedded Metal library for the ggml Metal backend (GGML_METAL_EMBED_LIBRARY).
//
// build_zerollama_mac.sh compiles Metal source (+ eliza-shipped kernels) into
// default.metallib and copies those bytes to ggml-metal-embed.metal for .incbin.
// ggml-metal-device.m detects MTLB magic and loads via newLibraryWithData.
//
// Upstream ollama instead embeds UTF-8 Metal source for JIT newLibraryWithSource;
// that path still works if the embed is text.
//
// Manual source-only regen (not used by Mac production builds):
//
//	GOFLAGS=-mod=mod go generate ./ml/backend/ggml/ggml/src/ggml-metal/
//
// Why metallib embed: eliza-shipped kernels (TBQ/QJL/etc.) must ship precompiled;
// treating MTLB bytes as UTF-8 source returns nil → newLibraryWithSource aborts →
// bootstrap /info dies → total_vram=0. See docs/apple-silicon-metal.md.
//
//go:generate sh -c "if [ -f ggml-metal.metal ]; then { echo // Code generated by 'go generate'. DO NOT EDIT.; sed -e '/__embed_ggml-common.h__/r ../ggml-common.h' -e '/__embed_ggml-common.h__/d' -e '/#include \"ggml-metal-impl.h\"/r ggml-metal-impl.h' -e '/#include \"ggml-metal-impl.h\"/d' ggml-metal.metal; } >ggml-metal-embed.metal; else echo 'skip ggml-metal-embed: ggml-metal.metal removed in b10615 (kernels/*.metal)'; fi"

// #cgo CXXFLAGS: -std=c++17
// #cgo CPPFLAGS: -DGGML_METAL_NDEBUG -DGGML_METAL_EMBED_LIBRARY -DGGML_METAL_HAS_BF16 -I.. -I../../include
// #cgo LDFLAGS: -framework Metal -framework MetalKit -framework IOSurface
import "C"
