// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: training.proto

package trainingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobKind int32

const (
	JobKind_JOB_KIND_UNSPECIFIED JobKind = 0
	JobKind_JOB_KIND_TRAIN       JobKind = 1
	JobKind_JOB_KIND_RUN_SCRIPT  JobKind = 2
)

// Enum value maps for JobKind.
var (
	JobKind_name = map[int32]string{
		0: "JOB_KIND_UNSPECIFIED",
		1: "JOB_KIND_TRAIN",
		2: "JOB_KIND_RUN_SCRIPT",
	}
	JobKind_value = map[string]int32{
		"JOB_KIND_UNSPECIFIED": 0,
		"JOB_KIND_TRAIN":       1,
		"JOB_KIND_RUN_SCRIPT":  2,
	}
)

func (x JobKind) Enum() *JobKind {
	p := new(JobKind)
	*p = x
	return p
}

func (x JobKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobKind) Descriptor() protoreflect.EnumDescriptor {
	return file_training_proto_enumTypes[0].Descriptor()
}

func (JobKind) Type() protoreflect.EnumType {
	return &file_training_proto_enumTypes[0]
}

func (x JobKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobKind.Descriptor instead.
func (JobKind) EnumDescriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_training_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	// JSON object: device, cuda_available, model_loaded, queue (legacy ping fields).
	ExtrasJson    string `protobuf:"bytes,2,opt,name=extras_json,json=extrasJson,proto3" json:"extras_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_training_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetExtrasJson() string {
	if x != nil {
		return x.ExtrasJson
	}
	return ""
}

type SubmitJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  JobKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=ollama.training.v1.JobKind" json:"kind,omitempty"`
	// JSON-encoded payload matching legacy training worker shapes (model paths, dataset, etc.).
	PayloadJson   string `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_training_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitJobRequest) GetKind() JobKind {
	if x != nil {
		return x.Kind
	}
	return JobKind_JOB_KIND_UNSPECIFIED
}

func (x *SubmitJobRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_training_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_training_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{4}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *JobInfo               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_training_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{5}
}

func (x *JobStatusResponse) GetJob() *JobInfo {
	if x != nil {
		return x.Job
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_training_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{6}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_training_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{7}
}

func (x *CancelJobResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_training_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{8}
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_training_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{9}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind            JobKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=ollama.training.v1.JobKind" json:"kind,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // pending, running, completed, failed, cancelled
	Progress        float64                `protobuf:"fixed64,4,opt,name=progress,proto3" json:"progress,omitempty"`
	ProgressMessage string                 `protobuf:"bytes,5,opt,name=progress_message,json=progressMessage,proto3" json:"progress_message,omitempty"`
	ResultJson      string                 `protobuf:"bytes,6,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // set when completed
	Error           string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	SubmittedAt     string                 `protobuf:"bytes,8,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	StartedAt       string                 `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt     string                 `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_training_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{10}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetKind() JobKind {
	if x != nil {
		return x.Kind
	}
	return JobKind_JOB_KIND_UNSPECIFIED
}

func (x *JobInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobInfo) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *JobInfo) GetProgressMessage() string {
	if x != nil {
		return x.ProgressMessage
	}
	return ""
}

func (x *JobInfo) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *JobInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobInfo) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

func (x *JobInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *JobInfo) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty = all jobs (use sparingly). Prefer filtering to one job.
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_training_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{11}
}

func (x *StreamEventsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type TrainingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*TrainingEvent_Progress
	//	*TrainingEvent_Completed
	//	*TrainingEvent_Failed
	//	*TrainingEvent_Oom
	Event         isTrainingEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingEvent) Reset() {
	*x = TrainingEvent{}
	mi := &file_training_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingEvent) ProtoMessage() {}

func (x *TrainingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingEvent.ProtoReflect.Descriptor instead.
func (*TrainingEvent) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{12}
}

func (x *TrainingEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TrainingEvent) GetEvent() isTrainingEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TrainingEvent) GetProgress() *ProgressEvent {
	if x != nil {
		if x, ok := x.Event.(*TrainingEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *TrainingEvent) GetCompleted() *JobCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*TrainingEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *TrainingEvent) GetFailed() *JobFailedEvent {
	if x != nil {
		if x, ok := x.Event.(*TrainingEvent_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *TrainingEvent) GetOom() *OOMEvent {
	if x != nil {
		if x, ok := x.Event.(*TrainingEvent_Oom); ok {
			return x.Oom
		}
	}
	return nil
}

type isTrainingEvent_Event interface {
	isTrainingEvent_Event()
}

type TrainingEvent_Progress struct {
	Progress *ProgressEvent `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type TrainingEvent_Completed struct {
	Completed *JobCompletedEvent `protobuf:"bytes,3,opt,name=completed,proto3,oneof"`
}

type TrainingEvent_Failed struct {
	Failed *JobFailedEvent `protobuf:"bytes,4,opt,name=failed,proto3,oneof"`
}

type TrainingEvent_Oom struct {
	Oom *OOMEvent `protobuf:"bytes,5,opt,name=oom,proto3,oneof"`
}

func (*TrainingEvent_Progress) isTrainingEvent_Event() {}

func (*TrainingEvent_Completed) isTrainingEvent_Event() {}

func (*TrainingEvent_Failed) isTrainingEvent_Event() {}

func (*TrainingEvent_Oom) isTrainingEvent_Event() {}

type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pct           float64                `protobuf:"fixed64,1,opt,name=pct,proto3" json:"pct,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_training_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{13}
}

func (x *ProgressEvent) GetPct() float64 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *ProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobCompletedEvent) Reset() {
	*x = JobCompletedEvent{}
	mi := &file_training_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCompletedEvent) ProtoMessage() {}

func (x *JobCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCompletedEvent.ProtoReflect.Descriptor instead.
func (*JobCompletedEvent) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{14}
}

func (x *JobCompletedEvent) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type JobFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFailedEvent) Reset() {
	*x = JobFailedEvent{}
	mi := &file_training_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFailedEvent) ProtoMessage() {}

func (x *JobFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFailedEvent.ProtoReflect.Descriptor instead.
func (*JobFailedEvent) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{15}
}

func (x *JobFailedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OOMEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OOMEvent) Reset() {
	*x = OOMEvent{}
	mi := &file_training_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OOMEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OOMEvent) ProtoMessage() {}

func (x *OOMEvent) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OOMEvent.ProtoReflect.Descriptor instead.
func (*OOMEvent) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{16}
}

func (x *OOMEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadRequest) Reset() {
	*x = UnloadRequest{}
	mi := &file_training_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadRequest) ProtoMessage() {}

func (x *UnloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadRequest.ProtoReflect.Descriptor instead.
func (*UnloadRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{17}
}

type UnloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadResponse) Reset() {
	*x = UnloadResponse{}
	mi := &file_training_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadResponse) ProtoMessage() {}

func (x *UnloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadResponse.ProtoReflect.Descriptor instead.
func (*UnloadResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{18}
}

func (x *UnloadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AckVRAMHeadroomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckVRAMHeadroomRequest) Reset() {
	*x = AckVRAMHeadroomRequest{}
	mi := &file_training_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckVRAMHeadroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckVRAMHeadroomRequest) ProtoMessage() {}

func (x *AckVRAMHeadroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckVRAMHeadroomRequest.ProtoReflect.Descriptor instead.
func (*AckVRAMHeadroomRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{19}
}

func (x *AckVRAMHeadroomRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type AckVRAMHeadroomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckVRAMHeadroomResponse) Reset() {
	*x = AckVRAMHeadroomResponse{}
	mi := &file_training_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckVRAMHeadroomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckVRAMHeadroomResponse) ProtoMessage() {}

func (x *AckVRAMHeadroomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckVRAMHeadroomResponse.ProtoReflect.Descriptor instead.
func (*AckVRAMHeadroomResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{20}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_training_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{21}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_training_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{22}
}

var File_training_proto protoreflect.FileDescriptor

const file_training_proto_rawDesc = "" +
	"\n" +
	"\x0etraining.proto\x12\x12ollama.training.v1\"\x0f\n" +
	"\rHealthRequest\"I\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vextras_json\x18\x02 \x01(\tR\n" +
	"extrasJson\"f\n" +
	"\x10SubmitJobRequest\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.ollama.training.v1.JobKindR\x04kind\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"B\n" +
	"\x11JobStatusResponse\x12-\n" +
	"\x03job\x18\x01 \x01(\v2\x1b.ollama.training.v1.JobInfoR\x03job\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"1\n" +
	"\x11CancelJobResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"\x11\n" +
	"\x0fListJobsRequest\"C\n" +
	"\x10ListJobsResponse\x12/\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1b.ollama.training.v1.JobInfoR\x04jobs\"\xcc\x02\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.ollama.training.v1.JobKindR\x04kind\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x01R\bprogress\x12)\n" +
	"\x10progress_message\x18\x05 \x01(\tR\x0fprogressMessage\x12\x1f\n" +
	"\vresult_json\x18\x06 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12!\n" +
	"\fsubmitted_at\x18\b \x01(\tR\vsubmittedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\tR\vcompletedAt\",\n" +
	"\x13StreamEventsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xa7\x02\n" +
	"\rTrainingEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12?\n" +
	"\bprogress\x18\x02 \x01(\v2!.ollama.training.v1.ProgressEventH\x00R\bprogress\x12E\n" +
	"\tcompleted\x18\x03 \x01(\v2%.ollama.training.v1.JobCompletedEventH\x00R\tcompleted\x12<\n" +
	"\x06failed\x18\x04 \x01(\v2\".ollama.training.v1.JobFailedEventH\x00R\x06failed\x120\n" +
	"\x03oom\x18\x05 \x01(\v2\x1c.ollama.training.v1.OOMEventH\x00R\x03oomB\a\n" +
	"\x05event\";\n" +
	"\rProgressEvent\x12\x10\n" +
	"\x03pct\x18\x01 \x01(\x01R\x03pct\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x11JobCompletedEvent\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\"&\n" +
	"\x0eJobFailedEvent\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"$\n" +
	"\bOOMEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0f\n" +
	"\rUnloadRequest\"(\n" +
	"\x0eUnloadResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"/\n" +
	"\x16AckVRAMHeadroomRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x19\n" +
	"\x17AckVRAMHeadroomResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse*P\n" +
	"\aJobKind\x12\x18\n" +
	"\x14JOB_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eJOB_KIND_TRAIN\x10\x01\x12\x17\n" +
	"\x13JOB_KIND_RUN_SCRIPT\x10\x022\xb8\x06\n" +
	"\x0eTrainingDaemon\x12O\n" +
	"\x06Health\x12!.ollama.training.v1.HealthRequest\x1a\".ollama.training.v1.HealthResponse\x12X\n" +
	"\tSubmitJob\x12$.ollama.training.v1.SubmitJobRequest\x1a%.ollama.training.v1.SubmitJobResponse\x12X\n" +
	"\tJobStatus\x12$.ollama.training.v1.JobStatusRequest\x1a%.ollama.training.v1.JobStatusResponse\x12X\n" +
	"\tCancelJob\x12$.ollama.training.v1.CancelJobRequest\x1a%.ollama.training.v1.CancelJobResponse\x12U\n" +
	"\bListJobs\x12#.ollama.training.v1.ListJobsRequest\x1a$.ollama.training.v1.ListJobsResponse\x12\\\n" +
	"\fStreamEvents\x12'.ollama.training.v1.StreamEventsRequest\x1a!.ollama.training.v1.TrainingEvent0\x01\x12O\n" +
	"\x06Unload\x12!.ollama.training.v1.UnloadRequest\x1a\".ollama.training.v1.UnloadResponse\x12j\n" +
	"\x0fAckVRAMHeadroom\x12*.ollama.training.v1.AckVRAMHeadroomRequest\x1a+.ollama.training.v1.AckVRAMHeadroomResponse\x12U\n" +
	"\bShutdown\x12#.ollama.training.v1.ShutdownRequest\x1a$.ollama.training.v1.ShutdownResponseB6Z4github.com/ollama/ollama/x/trainingworker/trainingpbb\x06proto3"

var (
	file_training_proto_rawDescOnce sync.Once
	file_training_proto_rawDescData []byte
)

func file_training_proto_rawDescGZIP() []byte {
	file_training_proto_rawDescOnce.Do(func() {
		file_training_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_training_proto_rawDesc), len(file_training_proto_rawDesc)))
	})
	return file_training_proto_rawDescData
}

var file_training_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_training_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_training_proto_goTypes = []any{
	(JobKind)(0),                    // 0: ollama.training.v1.JobKind
	(*HealthRequest)(nil),           // 1: ollama.training.v1.HealthRequest
	(*HealthResponse)(nil),          // 2: ollama.training.v1.HealthResponse
	(*SubmitJobRequest)(nil),        // 3: ollama.training.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),       // 4: ollama.training.v1.SubmitJobResponse
	(*JobStatusRequest)(nil),        // 5: ollama.training.v1.JobStatusRequest
	(*JobStatusResponse)(nil),       // 6: ollama.training.v1.JobStatusResponse
	(*CancelJobRequest)(nil),        // 7: ollama.training.v1.CancelJobRequest
	(*CancelJobResponse)(nil),       // 8: ollama.training.v1.CancelJobResponse
	(*ListJobsRequest)(nil),         // 9: ollama.training.v1.ListJobsRequest
	(*ListJobsResponse)(nil),        // 10: ollama.training.v1.ListJobsResponse
	(*JobInfo)(nil),                 // 11: ollama.training.v1.JobInfo
	(*StreamEventsRequest)(nil),     // 12: ollama.training.v1.StreamEventsRequest
	(*TrainingEvent)(nil),           // 13: ollama.training.v1.TrainingEvent
	(*ProgressEvent)(nil),           // 14: ollama.training.v1.ProgressEvent
	(*JobCompletedEvent)(nil),       // 15: ollama.training.v1.JobCompletedEvent
	(*JobFailedEvent)(nil),          // 16: ollama.training.v1.JobFailedEvent
	(*OOMEvent)(nil),                // 17: ollama.training.v1.OOMEvent
	(*UnloadRequest)(nil),           // 18: ollama.training.v1.UnloadRequest
	(*UnloadResponse)(nil),          // 19: ollama.training.v1.UnloadResponse
	(*AckVRAMHeadroomRequest)(nil),  // 20: ollama.training.v1.AckVRAMHeadroomRequest
	(*AckVRAMHeadroomResponse)(nil), // 21: ollama.training.v1.AckVRAMHeadroomResponse
	(*ShutdownRequest)(nil),         // 22: ollama.training.v1.ShutdownRequest
	(*ShutdownResponse)(nil),        // 23: ollama.training.v1.ShutdownResponse
}
var file_training_proto_depIdxs = []int32{
	0,  // 0: ollama.training.v1.SubmitJobRequest.kind:type_name -> ollama.training.v1.JobKind
	11, // 1: ollama.training.v1.JobStatusResponse.job:type_name -> ollama.training.v1.JobInfo
	11, // 2: ollama.training.v1.ListJobsResponse.jobs:type_name -> ollama.training.v1.JobInfo
	0,  // 3: ollama.training.v1.JobInfo.kind:type_name -> ollama.training.v1.JobKind
	14, // 4: ollama.training.v1.TrainingEvent.progress:type_name -> ollama.training.v1.ProgressEvent
	15, // 5: ollama.training.v1.TrainingEvent.completed:type_name -> ollama.training.v1.JobCompletedEvent
	16, // 6: ollama.training.v1.TrainingEvent.failed:type_name -> ollama.training.v1.JobFailedEvent
	17, // 7: ollama.training.v1.TrainingEvent.oom:type_name -> ollama.training.v1.OOMEvent
	1,  // 8: ollama.training.v1.TrainingDaemon.Health:input_type -> ollama.training.v1.HealthRequest
	3,  // 9: ollama.training.v1.TrainingDaemon.SubmitJob:input_type -> ollama.training.v1.SubmitJobRequest
	5,  // 10: ollama.training.v1.TrainingDaemon.JobStatus:input_type -> ollama.training.v1.JobStatusRequest
	7,  // 11: ollama.training.v1.TrainingDaemon.CancelJob:input_type -> ollama.training.v1.CancelJobRequest
	9,  // 12: ollama.training.v1.TrainingDaemon.ListJobs:input_type -> ollama.training.v1.ListJobsRequest
	12, // 13: ollama.training.v1.TrainingDaemon.StreamEvents:input_type -> ollama.training.v1.StreamEventsRequest
	18, // 14: ollama.training.v1.TrainingDaemon.Unload:input_type -> ollama.training.v1.UnloadRequest
	20, // 15: ollama.training.v1.TrainingDaemon.AckVRAMHeadroom:input_type -> ollama.training.v1.AckVRAMHeadroomRequest
	22, // 16: ollama.training.v1.TrainingDaemon.Shutdown:input_type -> ollama.training.v1.ShutdownRequest
	2,  // 17: ollama.training.v1.TrainingDaemon.Health:output_type -> ollama.training.v1.HealthResponse
	4,  // 18: ollama.training.v1.TrainingDaemon.SubmitJob:output_type -> ollama.training.v1.SubmitJobResponse
	6,  // 19: ollama.training.v1.TrainingDaemon.JobStatus:output_type -> ollama.training.v1.JobStatusResponse
	8,  // 20: ollama.training.v1.TrainingDaemon.CancelJob:output_type -> ollama.training.v1.CancelJobResponse
	10, // 21: ollama.training.v1.TrainingDaemon.ListJobs:output_type -> ollama.training.v1.ListJobsResponse
	13, // 22: ollama.training.v1.TrainingDaemon.StreamEvents:output_type -> ollama.training.v1.TrainingEvent
	19, // 23: ollama.training.v1.TrainingDaemon.Unload:output_type -> ollama.training.v1.UnloadResponse
	21, // 24: ollama.training.v1.TrainingDaemon.AckVRAMHeadroom:output_type -> ollama.training.v1.AckVRAMHeadroomResponse
	23, // 25: ollama.training.v1.TrainingDaemon.Shutdown:output_type -> ollama.training.v1.ShutdownResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_training_proto_init() }
func file_training_proto_init() {
	if File_training_proto != nil {
		return
	}
	file_training_proto_msgTypes[12].OneofWrappers = []any{
		(*TrainingEvent_Progress)(nil),
		(*TrainingEvent_Completed)(nil),
		(*TrainingEvent_Failed)(nil),
		(*TrainingEvent_Oom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_training_proto_rawDesc), len(file_training_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_training_proto_goTypes,
		DependencyIndexes: file_training_proto_depIdxs,
		EnumInfos:         file_training_proto_enumTypes,
		MessageInfos:      file_training_proto_msgTypes,
	}.Build()
	File_training_proto = out.File
	file_training_proto_goTypes = nil
	file_training_proto_depIdxs = nil
}
