"""Optional .env export of calibrated VRAM_ESTIMATE_FACTOR (Phase 13)."""

from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Any

from runtime.vram_autotune_persist import (
    _atomic_write,
    _factor_from_entry,
    _read_state,
    autotune_state_dir,
    vram_autotune_persist_enabled,
)


def vram_factor_export_enabled() -> bool:
    """On when probe calibration runs; disable only via VRAM_ESTIMATE_FACTOR_EXPORT=0."""
    v = os.environ.get(
        "ZEROLLAMA_RUNTIME_VRAM_ESTIMATE_FACTOR_EXPORT", ""
    ).strip().lower()
    if v in ("0", "false", "no", "off"):
        return False
    from runtime.vram_calibration import vram_probe_calibrate_enabled

    return vram_probe_calibrate_enabled()


def export_last_factor_path() -> Path:
    override = os.environ.get(
        "ZEROLLAMA_RUNTIME_VRAM_ESTIMATE_FACTOR_EXPORT_PATH", ""
    ).strip()
    if override:
        return Path(override).expanduser()
    return autotune_state_dir() / "vram_estimate_factor.env"


def export_catalog_path() -> Path:
    override = os.environ.get(
        "ZEROLLAMA_RUNTIME_VRAM_ESTIMATE_FACTOR_CATALOG", ""
    ).strip()
    if override:
        return Path(override).expanduser()
    return autotune_state_dir() / "vram_autotune_factors.env"


def _format_factor(value: float) -> str:
    return f"{max(0.1, min(3.0, float(value))):g}"


def export_last_calibration(
    factor: float,
    *,
    model: str | Path,
    observed_bytes: int | None = None,
    estimated_raw_bytes: int | None = None,
) -> bool:
    """Write a sourceable .env for the last probed load."""
    if not vram_factor_export_enabled():
        return False
    model_s = str(Path(model).expanduser().resolve())
    lines = [
        "# Generated by zerollama-runtime VRAM calibration.",
        "# Replaces ZEROLLAMA_RUNTIME_VRAM_ESTIMATE_FACTOR (do not multiply on top of autotune).",
        f"# model: {model_s}",
        f"# updated_at: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}",
    ]
    if observed_bytes is not None and estimated_raw_bytes:
        lines.append(
            f"# observed/raw ≈ {observed_bytes}/{estimated_raw_bytes}"
        )
    lines.append(
        f"export ZEROLLAMA_RUNTIME_VRAM_ESTIMATE_FACTOR={_format_factor(factor)}"
    )
    lines.append("")
    return _atomic_write(export_last_factor_path(), "\n".join(lines))


def export_factor_catalog() -> bool:
    """Regenerate per-model reference .env from persisted autotune state."""
    if not vram_factor_export_enabled():
        return False
    if not vram_autotune_persist_enabled():
        return False
    state = _read_state()
    if state is None:
        return False
    models: dict[str, Any] = state.get("models") or {}
    if not isinstance(models, dict) or not models:
        return False
    lines = [
        "# Generated by zerollama-runtime — per-model VRAM estimate factors.",
        "# Autotune persist applies these in-process; export is for manual env setup.",
        "# Uncomment ONE export line for the GGUF you load, or use vram_estimate_factor.env.",
        "",
    ]
    last = state.get("last_model")
    for key in sorted(models.keys()):
        factor = _factor_from_entry(models.get(key))
        if factor is None:
            continue
        marker = " (last calibration)" if key == last else ""
        lines.append(f"# model: {key}{marker}")
        lines.append(
            f"# export ZEROLLAMA_RUNTIME_VRAM_ESTIMATE_FACTOR={_format_factor(factor)}"
        )
        lines.append("")
    if isinstance(last, str):
        factor = _factor_from_entry(models.get(last))
        if factor is not None:
            lines.extend(
                [
                    "# Active export for last calibrated model:",
                    f"export ZEROLLAMA_RUNTIME_VRAM_ESTIMATE_FACTOR={_format_factor(factor)}",
                    f"# model: {last}",
                    "",
                ]
            )
    return _atomic_write(export_catalog_path(), "\n".join(lines))


def _unlink_export_path(path: Path) -> None:
    for candidate in (path, path.with_suffix(path.suffix + ".tmp")):
        try:
            if candidate.is_file():
                candidate.unlink()
        except OSError:
            pass


def clear_export_files() -> None:
    """Remove generated .env files (e.g. when autotune state is cleared)."""
    _unlink_export_path(export_last_factor_path())
    _unlink_export_path(export_catalog_path())


def export_status() -> dict[str, Any]:
    last = export_last_factor_path()
    catalog = export_catalog_path()
    return {
        "enabled": vram_factor_export_enabled(),
        "last_export_path": str(last),
        "last_export_exists": last.is_file(),
        "catalog_path": str(catalog),
        "catalog_exists": catalog.is_file(),
        "note": (
            "Sourced VRAM_ESTIMATE_FACTOR is ignored when autotune has a factor for "
            "the loaded GGUF; disable AUTOTUNE or clear STATE_DIR to use env only."
        ),
    }
